~# *** C:\Timon_emme\HELMET\sijoittelu\Database\batin_tyhjafillariverkko.mac
~#
~#  luetaan TYHJAAN SKENAARIOON verkko, linjasto ja kaantymiset
~#  TE 6.11.2018
~#
 off=11
batchin=
reports=
~#
~# ** luetaan kulkutavat
~! del  d201.in
~! copy d201_testi.in  d201.in 
 on=11
 2.01
 1
~?q=2
 2
 q
 off=11
~# ** luetaan verkko
~! del  d211.in
~! copy d211_testi.in  d211.in
 on=11
 2.11
~?q=2
 2
 off=11
~#
 sta
 s=
~#
~/ *** batin_tyhjafillariverkko.mac ***
